deploymentMode: SimpleScalable

loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  querier:
    max_concurrent: 4

  pattern_ingester:
    enabled: true

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention

  storage:
    type: s3
    bucketNames:
      chunks: logging-chunk
      ruler: logging-ruler
      admin: logging-admin
    s3:
      endpoint: http://minio.deplatform.local:32000
      region: us-west-2
      accessKeyId: ${LOKI_ACCESS_KEY}
      secretAccessKey: ${LOKI_SECRET_KEY}
      s3ForcePathStyle: true
      insecure: true
      http_config: {}

backend:
  replicas: 1
  extraEnv:
    - name: LOKI_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: services.logging.raw-loki-access-key
          key: LOKI_ACCESS_KEY
    - name: LOKI_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: services.logging.raw-loki-secret-key
          key: LOKI_SECRET_KEY
read:
  replicas: 1
write:
  replicas: 1

minio:
  enabled: false

gateway:
  service:
    type: LoadBalancer

