apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
        - name: hive-schema-init
          image: hive-iceberg:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: HIVE_HOME
              value: "/opt/hive"
            - name: HADOOP_HOME
              value: "/opt/hadoop"
          command:
            - sh
          args:
            - -c
            - |
              echo "Initializing or upgrading Hive schema...";
              /opt/hive/bin/schematool -dbType postgres -initSchema || /opt/hive/bin/schematool -dbType postgres -upgradeSchema;
              echo "Schema initialization or upgrade complete!";
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf
      containers:
        - name: hive-metastore
          image: hive-iceberg:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9083
          env:
            - name: HIVE_METASTORE_PORT
              value: "9083"
            - name: HIVE_HOME
              value: "/opt/hive"
            - name: HADOOP_HOME
              value: "/opt/hadoop"
          command:
            - /opt/hive/bin/hive
          args:
            - --service
            - metastore
            - -p
            - "9083"
          volumeMounts:
            - name: hive-config
              mountPath: /opt/hive/conf
      volumes:
        - name: hive-config
          secret:
            secretName: services.iceberg.raw-hive-conf
