grafana:
  adminPassword: ""
  admin:
    existingSecret: "services.monitoring.grafana-credentials"
    userKey: admin-user
    passwordKey: admin-password
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.logging.svc.cluster.local
      access: proxy
      isDefault: false
