grafana:
  admin:
    existingSecret: "services.monitoring.grafana-credentials"
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.logging.svc.cluster.local
      access: proxy
      isDefault: false
