apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: iceberg
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: iceberg
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: postgres-pv
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
