apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-secret-access-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-secret-access-rolebinding
subjects:
  - kind: ServiceAccount
    name: airflow-migrate-database-job
    namespace: airflow
  - kind: ServiceAccount
    name: airflow
    namespace: airflow
  - kind: ServiceAccount
    name: airflow-scheduler
    namespace: airflow
  - kind: ServiceAccount
    name: airflow-worker
    namespace: airflow
  - kind: ServiceAccount
    name: airflow-dag-processor
    namespace: airflow
roleRef:
  kind: ClusterRole
  name: airflow-secret-access-role
  apiGroup: rbac.authorization.k8s.io
