executor: KubernetesExecutor
images:
  airflow:
    repository: airflow
    tag: dev
    pullPolicy: IfNotPresent
useStandardNaming: true
logs:
  persistence:
    size: 35Gi

secret:
  - envName: "AIRFLOW_CONN_MINIO"
    secretName: "services.airflow.minio-conn"
    secretKey: "AIRFLOW_CONN_MINIO"

webserverSecretKeySecretName: services.airflow.web-secret

#pgbouncer:
#  enabled: true
#  maxClientConn: 100
#  metadataPoolSize: 10
#  resultBackendPoolSize: 5

env:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "True"
  - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
    value: "s3://airflow/logs"
  - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
    value: "minio"
  - name: AIRFLOW__LOGGING__COLORED_CONSOLE_LOGS
    value: "False"
  - name: AIRFLOW__LOGGING__ENCRYPT_S3_LOGS
    value: "False"

dags:
  gitSync:
    enabled: true
    repo: git@github.com:kmacdonald76/de_airflow.git
    branch: main
    subPath: ""
    depth: 1
    period: 60s
    sshKeySecret: services.airflow.git-sync-key
    knownHosts: |
      github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
