apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-session
  namespace: flink
  labels:
    component: jobmanager
spec:
  image: flink-iceberg-hive:dev
  flinkVersion: v1_20
  serviceAccount: flink
  jobManager:
    resource:
      cpu: 1
      memory: "2Gi"
  taskManager:
    resource:
      cpu: 2
      memory: "4Gi"
  flinkConfiguration:
    jobmanager.memory.process.size: 2g
    taskmanager.memory.process.size: 4g
    jobmanager.archive.fs.dir: s3a://flink-apps/completed-jobs/
    taskmanager.numberOfTaskSlots: 2
    sqlgateway.workers: 2
    iceberg.catalog.hive.type: hive
    iceberg.catalog.hive.uri: thrift://metastore.deplatform.local:32083
    iceberg.catalog.hive.warehouse: s3a://iceberg/
    flink.hadoop.fs.s3a.endpoint: http://minio.deplatform.local:32000
    flink.hadoop.fs.s3a.path.style.access: true
    fs.s3a.endpoint: http://minio.deplatform.local:32000
    fs.s3a.path.style.access: true
    s3.endpoint: http://minio.deplatform.local:32000
    s3.path-style: true
    s3.path.style.access: true
    logger.hadoop.level: TRACE
    classloader.parent-first-patterns.additional: com.codahale.metrics
  podTemplate:
    spec:
      volumes:
      - name: hive-conf
        secret:
          secretName: services.flink.raw-hive-conf
      containers:
      - name: flink-main-container
        volumeMounts:
        - name: hive-conf
          mountPath: /opt/hive-conf
        envFrom:
          - secretRef:
              name: services.flink.raw-flink-properties
          - secretRef:
              name: services.flink.raw-aws-access-key
          - secretRef:
              name: services.flink.raw-aws-secret-key
